### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by noam-honig** [sboulema/GitBlamer#3]
Still getting this error in 0.1.15 - can you add some debug info - maybe write the stack to the output window so I can send it to you?

**Comment by sboulema** [comment]
Should be fixed in the latest release: https://github.com/sboulema/GitBlamer/releases/tag/v0.1.9

**Comment by noam-honig** [comment]
Still am getting this error some time - any way I can help you trace it? a log file or something?
![image](https://user-images.githubusercontent.com/16635859/41957382-6d735a3a-79ef-11e8-9426-0dbbd188b361.png)

**Comment by sboulema** [comment]
Should be really fixed in the latest release: https://github.com/sboulema/GitBlamer/releases/tag/v0.2.13

**Comment by noam-honig** [comment]
Didn't get it in the latest release yet :)
