### ISSUE TITLE
fatal: Path 'xxx' exists on disk, but not in 'yyyy'

### ISSUE THREAD

**Issue by noam-honig** [sboulema/GitBlamer#4]
When clicking back on the file called DataApiController I've got the compare window but with errors in it.
![image](https://user-images.githubusercontent.com/16635859/41505121-3e1cd9d8-720a-11e8-8b58-03a94c087035.png)
It does exist in both versions:
![image](https://user-images.githubusercontent.com/16635859/41505128-656a847c-720a-11e8-8c50-5a2e463d35d0.png)
![image](https://user-images.githubusercontent.com/16635859/41505129-72a4e83a-720a-11e8-8266-b4d58c516e86.png)
![image](https://user-images.githubusercontent.com/16635859/41505136-7c3a5592-720a-11e8-91eb-ffd41971a801.png)

I think there is a trimming issue, as in the error it calls the revision "4260c28" but in the history it's called "4260c28c" (with an extra c in the end)

you can download the repo I'm testing with at: https://github.com/fireflymigration/env.web

**Comment by sboulema** [comment]
Try the new release: https://github.com/sboulema/GitBlamer/releases/tag/v0.1.9

**Comment by noam-honig** [comment]
Still am getting this error - it seems that if I go to back in history it'll show.
![image](https://user-images.githubusercontent.com/16635859/41957421-8d5b9ccc-79ef-11e8-9143-99bd828ecfce.png)

**Comment by sboulema** [comment]
Try the new release: https://github.com/sboulema/GitBlamer/releases/tag/v0.2.13

**Comment by noam-honig** [comment]
Didn't get it in the latest release yet :)
