### ISSUE TITLE
The changes window flips between old and new showing old as new 

### ISSUE THREAD

**Issue by noam-honig** [sboulema/GitBlamer#7]
I'm using the Repo https://github.com/fireflymigration/env.web and the file DataApi.cs

I click "Previous revision" and I get commit b8c8323 on the left and 07c8ae3 on the right - so far it's great.
![image](https://user-images.githubusercontent.com/16635859/42131620-c13521fe-7d0e-11e8-8b7c-a07649a37c94.png)

Now I click "later revision"- it flips the compare so now we see 07c8ae3 on the left (as old, even that it's the newer one) and revision b8c8323 on the right (as new even that it's the older one)
![image](https://user-images.githubusercontent.com/16635859/42131623-c9c6ce58-7d0e-11e8-9ecf-79bb9f0e6059.png)

Same thing happens if I browser farther down the history path

**Comment by sboulema** [comment]
Grab the new release: https://github.com/sboulema/GitBlamer/releases/tag/v0.2.17

**Comment by noam-honig** [comment]
seems ok
