### ISSUE TITLE
The commit id is missing a character

### ISSUE THREAD

**Issue by noam-honig** [sboulema/GitBlamer#8]
Even though the commit is called 07c8ae31 ot only shows 07c8ae3 on the titles and details.
The commit name in history:
![image](https://user-images.githubusercontent.com/16635859/42131649-486596c2-7d0f-11e8-9cb0-247b67a3e535.png)

In the commit details
![image](https://user-images.githubusercontent.com/16635859/42131653-573d7b56-7d0f-11e8-8700-00747ee91981.png)

in the diff screen:
![image](https://user-images.githubusercontent.com/16635859/42131658-61c91526-7d0f-11e8-95b1-2c8b095c845e.png)

**Comment by sboulema** [comment]
Grab the new release: https://github.com/sboulema/GitBlamer/releases/tag/v0.2.17

**Comment by noam-honig** [comment]
Seems ok
